export const driver = [
  { id: 0, name: 'Hung', age: '28', liense: 'B2' },
  { id: 1, name: 'Tuan', age: '28', liense: 'B2' },
  { id: 2, name: 'Toan', age: '28', liense: 'B2' },
  { id: 3, name: 'Lan', age: '28', liense: 'B2' },
  { id: 4, name: 'Ngoc', age: '28', liense: 'B2' },
  { id: 5, name: 'Hung', age: '28', liense: 'B2' },
  { id: 6, name: 'Tuan', age: '28', liense: 'B2' },
  { id: 7, name: 'Toan', age: '28', liense: 'B2' },
  { id: 8, name: 'Lan', age: '28', liense: 'B2' },
  { id: 9, name: 'Ngoc', age: '28', liense: 'B2' },
  { id: 10, name: 'Hung', age: '28', liense: 'B2' },
  { id: 11, name: 'Tuan', age: '28', liense: 'B2' },
  { id: 12, name: 'Toan', age: '28', liense: 'B2' },
  { id: 13, name: 'Lan', age: '28', liense: 'B2' },
  { id: 14, name: 'Ngoc', age: '28', liense: 'B2' },
  { id: 15, name: 'Hung', age: '28', liense: 'B2' },
  { id: 16, name: 'Tuan', age: '28', liense: 'B2' },
  { id: 17, name: 'Toan', age: '28', liense: 'B2' },
  { id: 18, name: 'Lan', age: '28', liense: 'B2' },
  { id: 19, name: 'Ngoc', age: '28', liense: 'B2' },
  { id: 20, name: 'Hung', age: '28', liense: 'B2' },
  { id: 21, name: 'Tuan', age: '28', liense: 'B2' },
  { id: 22, name: 'Toan', age: '28', liense: 'B2' },
  { id: 23, name: 'Lan', age: '28', liense: 'B2' },
  { id: 24, name: 'Ngoc', age: '28', liense: 'B2' }
]
