export const KEYSTORE = {
  APP_CONFIGS: 'APP_CONFIGS',
  LIST_LANGUAGE: 'LIST_LANGUAGE',
  LANG_EN: 'LANG_EN',
  LOCALE: 'LOCALE',
  PAGE_PRIVACY: 'PAGE_PRIVACY',
  LOGIN: 'LOGIN',
  TOKEN_AUTHENTICATION: 'TOKEN_AUTHENTICATION',
  WALLET: 'WALLET',
  PINCODE: 'PINCODE',
  FINGERPRINT: 'FINGERPRINT',
  LIST_USER: 'LIST_USER'
}
